[colors.bright]
black = "#6C6F85"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#BCC0CC"
yellow = "#DF8E1D"
[colors.cursor]
cursor = "#DC8A78"
text = "#EFF1F5"

[colors.dim]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.hints.end]
background = "#6C6F85"
foreground = "#EFF1F5"

[colors.hints.start]
background = "#DF8E1D"
foreground = "#EFF1F5"

[colors.normal]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.primary]
background = "#f3f5f6"
bright_foreground = "#4C4F69"
dim_foreground = "#4C4F69"
foreground = "#1b2258"

[colors.search.focused_match]
background = "#40A02B"
foreground = "#EFF1F5"

[colors.search.matches]
background = "#6C6F85"
foreground = "#EFF1F5"

[colors.selection]
background = "#DC8A78"
text = "#EFF1F5"

[colors.vi_mode_cursor]
cursor = "#7287FD"
text = "#EFF1F5"

[font]
size = 11.0

[font.bold]
family = "BlexMono"
style = "Bold"

[font.normal]
family = "BlexMono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 1000

[terminal.shell]
# args = ["-l", "-c", "tmux attach -2 || tmux -2"]
args = ["-l"]
program = "/etc/profiles/per-user/kha/bin/zsh"

[window]
decorations = "full"
title = "Alacritty (zsh)"

[window.dimensions]
columns = 120
lines = 40
